# Generated by Django 3.1.7 on 2021-02-23 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_auto_20210224_0018'),
        ('staff', '0002_auto_20210224_0018'),
        ('documents', '0004_auto_20210223_2345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='order',
        ),
        migrations.AddField(
            model_name='document',
            name='client_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.order'),
        ),
        migrations.AlterField(
            model_name='document',
            name='creaеtion_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='staff.employee'),
        ),
    ]
