# Generated by Django 3.1.7 on 2021-02-23 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_auto_20210224_0018'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='creaеtion_date',
            new_name='creation_date',
        ),
    ]
