# Generated by Django 3.1.7 on 2021-03-08 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_auto_20210224_0107'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'verbose_name': 'Документ', 'verbose_name_plural': 'Документы'},
        ),
        migrations.AlterModelOptions(
            name='documenttype',
            options={'verbose_name': 'Тип документы', 'verbose_name_plural': 'Типы документов'},
        ),
    ]
