# Generated by Django 3.1.7 on 2021-02-22 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0001_initial'),
        ('clients', '0004_order_manager'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technical_task', models.CharField(max_length=10000)),
                ('cd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.employee')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.order')),
            ],
        ),
    ]
