# Generated by Django 3.1.7 on 2021-02-22 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='cd',
        ),
        migrations.AddField(
            model_name='project',
            name='creative_director',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='creative_director', to='staff.employee'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='project_manager',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='project_manager', to='staff.employee'),
            preserve_default=False,
        ),
    ]
