# Generated by Django 3.1.7 on 2021-02-23 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20210222_1916'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='order',
            new_name='client_order',
        ),
        migrations.AlterField(
            model_name='project',
            name='technical_task',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
