# Generated by Django 3.1.7 on 2021-02-22 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='priority',
            old_name='priotity_level',
            new_name='priority_level',
        ),
    ]
