# Generated by Django 3.1.7 on 2021-03-09 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_auto_20210224_0133'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeetask',
            options={'verbose_name': 'Задача сотрудника', 'verbose_name_plural': 'Задачи сотрудника'},
        ),
        migrations.AlterModelOptions(
            name='priority',
            options={'verbose_name': 'Приоритет', 'verbose_name_plural': 'Приоритеты'},
        ),
        migrations.AlterModelOptions(
            name='reportingtask',
            options={'verbose_name': 'Отчет по задаче', 'verbose_name_plural': 'Отчеты по задачам'},
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name': 'Статус', 'verbose_name_plural': 'Статусы'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Задача', 'verbose_name_plural': 'Задачи'},
        ),
    ]
